<?php

/**
 * @file
 * Exposes the Pin API system as nodes.
 */


/**
 * Implements hook_pinapi_relationships().
 */
function pinapi_node_pinapi_relationships() {
  $relationships['pinapi_group']['node'] = array(
    'title' => t('Node'),
    'help' => t('The node that is associated with a group.'),
    'base' => 'node',
    'base field' => 'nid',
    'handler' => 'pinapi_views_handler_relationship',
  );

  return $relationships;
}

/**
 * Implements hook_pinapi_prize_relationships().
 */
function pinapi_node_pinapi_prize_relationships() {
  $relationships['pinapi_prize']['node'] = array(
    'title' => t('Node'),
    'help' => t('The node that is associated with a prize.'),
    'base' => 'node',
    'base field' => 'nid',
    'handler' => 'pinapi_views_handler_relationship',
  );

  return $relationships;
}
