<?php

/**
 * @file
 * Exposes the Pin API system as nodes.
 */


/**
 * Implements hook_menu().
 */
function pinapi_node_menu() {
  return array(
    'admin/settings/pinapi/node' => array(
      'title' => 'Nodes',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pinapi_node_settings_form'),
      'access callback' => 'user_access',
      'access arguments' => array('administer pin api'),
      'file' => 'pinapi_node.admin.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
    ),
  );
}

/**
 * Implements hook_pinapi_relationships().
 */
function pinapi_node_pinapi_relationships() {
  $relationships['pinapi_group']['node'] = array(
    'title' => t('Node'),
    'help' => t('The node that is associated with a group.'),
    'base' => 'node',
    'base field' => 'nid',
    'handler' => 'pinapi_views_handler_relationship',
  );

  return $relationships;
}

/**
 * Implements hook_pinapi_prize_relationships().
 */
function pinapi_node_pinapi_prize_relationships() {
  $relationships['pinapi_prize']['node'] = array(
    'title' => t('Node'),
    'help' => t('The node that is associated with a prize.'),
    'base' => 'node',
    'base field' => 'nid',
    'handler' => 'pinapi_views_handler_relationship',
  );

  return $relationships;
}
