<?php

/**
 * @file
 * Exposes the Pin API system as nodes.
 */

require_once dirname(__FILE__) . '/pinapi_node.inc';

/**
 * Implements hook_menu().
 */
function pinapi_node_menu() {
  return array(
    'admin/settings/pinapi/node' => array(
      'title' => 'Nodes',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pinapi_node_settings_form'),
      'access callback' => 'user_access',
      'access arguments' => array('administer pin api'),
      'file' => 'pinapi_node.admin.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function pinapi_node_form_alter(&$form, &$form_state, $form_id) {
  if ( $form_id == 'pinapi_ui_prize_form' ) {
    // Load prize object.
    if ( !empty($form['pid']['#value']) ) {
      $prize = pinapi_prize_load($form['pid']['#value']);
    }

    $form['content_id'] = array(
      '#type' => 'select',
      '#title' => t('Node'),
      '#options' => pinapi_node_potential_references('prize'),
      '#default_value' => isset($prize->content_id) ? $prize->content_id : 0,
    );
  }

  if ( $form_id == 'pinapi_ui_group_form' ) {
    // Load group object.
    if ( !empty($form['gid']['#value']) ) {
      $group = pinapi_group_load($form['gid']['#value']);
    }

    $form['content_id'] = array(
      '#type' => 'select',
      '#title' => t('Node'),
      '#options' => pinapi_node_potential_references('group'),
      '#default_value' => isset($group->content_id) ? $group->content_id : 0,
    );
  }
}

/**
 * Implements hook_pinapi_prizeapi().
 */
function pinapi_node_pinapi_prizeapi($op, &$prize, $group = NULL, $account = NULL) {
  switch ( $op ) {
    case 'load':
      if ( $prize->content_type == 'node' && $node = node_load($prize->content_id) ) {
        $prize->node = $node;
      }
      break;
  }
}

/**
 * Implements hook_pinapi_relationships().
 */
function pinapi_node_pinapi_relationships() {
  $relationships['pinapi_group']['node'] = array(
    'title' => t('Node'),
    'help' => t('The node that is associated with a group.'),
    'base' => 'node',
    'base field' => 'nid',
    'handler' => 'pinapi_views_handler_relationship',
  );

  return $relationships;
}

/**
 * Implements hook_pinapi_prize_relationships().
 */
function pinapi_node_pinapi_prize_relationships() {
  $relationships['pinapi_prize']['node'] = array(
    'title' => t('Node'),
    'help' => t('The node that is associated with a prize.'),
    'base' => 'node',
    'base field' => 'nid',
    'handler' => 'pinapi_views_handler_relationship',
  );

  return $relationships;
}

/**
 * Implements hook_pinapi_prize_redeemed_view().
 */
function pinapi_node_pinapi_prize_redeemed_view($prize_redeemed) {
  return array(
    'pinapi_node' => array(
      '#value' => node_view($prize_redeemed->prize->node, FALSE, TRUE, TRUE),
    ),
  );
}

/**
 * Return an array of potential node references.
 */
function pinapi_node_potential_references($type) {
  $types = pinapi_node_types($type);
  
  $nodes = array('0' => t('- None -'));
  $result = db_query("SELECT nid, title FROM {node} WHERE type IN ('" . implode("', '", $types) . "')");
  while ( $node = db_fetch_object($result) ) {
    $nodes[$node->nid] = check_plain($node->title);
  }

  return $nodes;
}
