<?php

/**
 * @file
 * Report the status of Pin API
 */


/**
 * Implements hook_perm().
 */
function pinapi_report_perm() {
  return array('view pin api reports');
}

/**
 * Implements hook_menu().
 */
function pinapi_report_menu() {
  $items['admin/reports/pinapi'] = array(
    'title' => 'Pin API System Status',
    'description' => 'Provides reports about the Pin API system.',
    'page callback' => 'pinapi_report_page_view',
    'access arguments' => array('view pin api reports'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Page Callback: Returns Pin API System Report.
 */
function pinapi_report_page_view() {
  return __FUNCTION__;
  
  /*
  $result = db_query("SELECT * FROM {pinapi_pool} WHERE status = 1");

  while ( $pool = db_fetch_array($result) ) {
    $availability = array();
    $prizes = pinapi_pool_prizes($pool['pool_id']);
    foreach ( $prizes as $prize ) {
      $availability[] = $prize['name'] . ' (' . $prize['quantity'] . ' left x' . $prize['bias'] . ')';
    }

    $content['pool_' . $pool['pool_id']] = array(
      '#type' => 'item',
      '#title' => t('Pool @num', array('@num' => $pool['pool_id'])),
      '#value' => theme('item_list', $availability),
      '#weight' => 0,
    );
  }

  return drupal_render($content);
  */
}
