<?php

/**
 * @file
 * Provides integration of Pin API with rules.
 */


/**
 * Implements hook_pinapi_txn
 */
function pinapi_rules_pinapi_txn($op, &$txn) {
  $event = '';
  switch ( $op ) {
    case 'redeem':
      $event = 'pinapi_event_txn_redeem';
      break;
  }

  try {

    // Load wrapped user entity so we can act on the object.
    $txn->user = entity_metadata_wrapper('user', $txn->uid);

    // Invoke rules event.
    rules_invoke_event($event, $txn);
  }
  catch ( EntityMetadataWrapperException $e ) {

  }
}
