<?php 

/**
 * @file
 * Provides WebSaver PinAPI functionality.
 */

/**
 * Implements hook_pinapi_prize_redeemed_view().
 */
function pinapi_websaver_pinapi_prize_redeemed_view(&$prize, $teaser = FALSE, $page = FALSE) {
  if ( $prize['content_type'] == 'node' && variable_get('pinapi_websaver_enabled', FALSE) && websaver_node_types($prize['node']->type) ) {
    if ( !empty($prize['node']->websaver['campaign']) ) {
      $prize['content']['websaver'] = array(
        '#value' => theme('websaver_node_button', $prize['node'], $prize['code']),
        '#weight' => 1,
      );
    }
  }
}
