<?php

/**
 * @file
 * Provides PinAPI collecting functionality.
 */


/**
 * Implements hook_theme().
 */
function pinapi_collect_theme() {
  return array(
    'pinapi_collect_block' => array(
      'arguments' => array('account' => NULL, 'group' => NULL),
      'template' => 'block-pinapi-collect',
      'path' => drupal_get_path('module', 'pinapi_collect') . '/theme',
      'file' => 'theme.inc',
    ),
  );
}

/**
 * Implements hook_block().
 */
function pinapi_collect_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {

    case 'list':
      return array(
        array('info' => t('Pin API Collect')),
      );

    case 'configure':
      if ( user_access('administer pin api') ) {
        $groups = array('' => t('- None -'));
        foreach ( pinapi_group_get_groups() as $group ) {
          $groups[$group->gid] = $group->name;
        }
        $form['pinapi_collect_gid'] = array(
          '#type' => 'select',
          '#title' => t('Group'),
          '#options' => $groups,
          '#default_value' => variable_get('pinapi_collect_gid', ''),
        );
        $form['pinapi_collect_block_required'] = array(
          '#type' => 'textfield',
          '#title' => t('Required number of PINs'),
          '#description' => t('Number of PINs required before user is able to order a prize.'),
          '#size' => 40,
          '#maxlength' => 3,
          '#default_value' => variable_get('pinapi_collect_block_required', 15),
        );
      }
      return $form;

    case 'save':
      if ( $delta == 0 ) {
        variable_set('pinapi_collect_gid', $edit['pinapi_collect_gid']);
        variable_set('pinapi_collect_block_required', $edit['pinapi_collect_block_required']);
      }
      break;

    case 'view':
      $block = array();
      if ( $delta == 0 && user_access('redeem codes') && variable_get('pinapi_collect_gid', '') ) {
        $group = pinapi_group_load(variable_get('pinapi_collect_gid', 0));
        $user = user_load($GLOBALS['user']->uid);
        $block['subject'] = t('Pin API Collect');
        $block['content'] = theme('pinapi_collect_block', $user, $group);
      }
      return $block;
  }
}

