<?php

/**
 * @file
 * Provides an administrative ui for Pin API.
 */


/**
 * Implements hook_menu().
 */
function pinapi_ui_menu() {
  $admin_access = array('administer pin api');

  $items['admin/build/pinapi'] = array(
    'title' => 'Pin API',
    'description' => 'Create and maintain Pin API groups.',
    'page callback' => 'pinapi_ui_view_overview',
    'access arguments' => $admin_access,
    'file' => 'pinapi_ui.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/build/pinapi/overview'] = array(
    'title' => 'Overview',
    'weight' => -1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // Groups
  $items['admin/build/pinapi/groups'] = array(
    'title' => 'Groups',
    'page callback' => 'pinapi_ui_view_groups',
    'access arguments' => $admin_access,
    'file' => 'pinapi_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/build/pinapi/group/add'] = array(
    'title' => 'Add Group',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pinapi_ui_group_form'),
    'access arguments' => $admin_access,
    'file' => 'pinapi_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/build/pinapi/group/%pinapi_group/edit'] = array(
    'title' => 'Edit Group',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pinapi_ui_group_form', 4),
    'access arguments' => $admin_access,
    'file' => 'pinapi_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/build/pinapi/group/%pinapi_group/delete'] = array(
    'title' => 'Delete Group',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pinapi_ui_group_delete_form', 4),
    'access arguments' => $admin_access,
    'file' => 'pinapi_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/build/pinapi/group/%pinapi_group/calculate'] = array(
    'title' => 'Calculate Group',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pinapi_ui_group_calculate_form', 4),
    'access arguments' => $admin_access,
    'file' => 'pinapi_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );

  if ( module_exists('pinapi_prize') ) {
    $items['admin/build/pinapi/prizes'] = array(
      'title' => 'Prizes',
      'page callback' => 'pinapi_ui_view_prizes',
      'access arguments' => $admin_access,
      'file' => 'pinapi_ui.admin.inc',
      'type' => MENU_LOCAL_TASK,
    );
    
    $items['admin/build/pinapi/prize/add'] = array(
      'title' => 'Add Prize',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pinapi_ui_prize_form'),
      'access arguments' => $admin_access,
      'file' => 'pinapi_ui.admin.inc',
      'type' => MENU_CALLBACK,
    );

    $items['admin/build/pinapi/prize/%pinapi_prize/edit'] = array(
      'title' => 'Edit Prize',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pinapi_ui_prize_form', 4),
      'access arguments' => $admin_access,
      'file' => 'pinapi_ui.admin.inc',
      'type' => MENU_CALLBACK,
    );

    $items['admin/build/pinapi/prize/%pinapi_prize/delete'] = array(
      'title' => 'Delete Prize',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('pinapi_ui_prize_delete_form', 4),
      'access arguments' => $admin_access,
      'file' => 'pinapi_ui.admin.inc',
      'type' => MENU_CALLBACK,
    );
  }

  return $items;
}

/**
 * Include UI files.
 */
function pinapi_ui_includes() {
  drupal_add_css(drupal_get_path('module', 'pinapi_ui') . '/includes/pinapi_ui.css');
}
